### ISSUE TITLE
百度网盘失效了

### ISSUE THREAD

**Issue by QLMX** [349zzjau/ChinaHadoop_C6#1]

**Comment by world2025** [comment]
您好，代码里面的网盘链接失效了，请问能够再次分享一下吗？谢谢

**Comment by world2025** [comment]
> No description provide
您好！请问您解决了吗？

**Comment by QLMX** [comment]
没有解决

**Comment by world2025** [comment]
好吧

**Comment by world2025** [comment]
> 没有解决

请问你第七章的图像描述调试代码的时候出现问题了吗？我在运行train.py的文件的时候提示我说为找到输入文件，但是我已经转换成了tfrecord格式了

**Comment by world2025** [comment]
> > 没有解决
> 
> 请问你第七章的图像描述调试代码的时候出现问题了吗？我在运行train.py的文件的时候提示我说为找到输入文件，但是我已经转换成了tfrecord格式了

已解决，是我有个路径搞错了

**Comment by world2025** [comment]
@349zzjau 您好！. 百度网盘https://pan.baidu.com/s/1gfpCCwj的C6文件夹中下载SegmentationClassAug.rar, 并解压到当前目录，是这个云盘失效了
